name: diabetes_habits_app
description: App de hábitos para personas con diabetes
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
timezone: ^0.9.2
    
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

  # Para internacionalización
  localization:
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart
